apiVersion: apps/v1
kind: Deployment
metadata:
  name: metronome-load-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metronome-load-test
  template:
    metadata:
      labels:
        app: metronome-load-test
    spec:
      securityContext:
          runAsNonRoot: true
          runAsUser: 1000
          runAsGroup: 1000
          seccompProfile:
            type: RuntimeDefault
      containers:
        - name: locust
          image: metronome-load-test:0.1.2
          imagePullPolicy: IfNotPresent
          env:
            - name: LOCUST_HOST
              value: "http://metronome-simulator.autoscaling-lab.svc.cluster.local"
            - name: BATTLE_REQUEST_TIMEOUT_SECONDS
              value: "30"  
          args:
            - -f
            - /home/locust/locustfile.py
            - --web-host
            - 0.0.0.0
          ports:
            - name: web
              containerPort: 8089
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 1000m
              memory: 512Mi
          volumeMounts:
            - name: tmp
              mountPath: /tmp
          startupProbe:
            httpGet:
              path: /
              port: web
            failureThreshold: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: web
            failureThreshold: 3
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: web
            failureThreshold: 3
            periodSeconds: 10
      volumes:
        - name: tmp
          emptyDir: {}
