apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: metronome-simulator
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind:       Deployment
    name:       metronome-simulator
  updatePolicy:
    updateMode: "Off"
  resourcePolicy:
    containerPolicies:
    - containerName: "simulator"
      controlledResources:
      - cpu
      - memory
      controlledValues: RequestsOnly
