apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"argoproj.io/v1alpha1","kind":"Application","metadata":{"annotations":{},"name":"metronome-prod","namespace":"argocd"},"spec":{"destination":{"namespace":"metronome-prod","server":"https://kubernetes.default.svc"},"project":"metronome-prod","source":{"path":"k8s/gitops/overlays/prod","repoURL":"https://github.com/kirbytran12324/autoscaling-final-lab.git","targetRevision":"main"},"syncPolicy":{"automated":{"enabled":true,"prune":true,"selfHeal":true}}}}
  creationTimestamp: "2026-09-21T06:48:01Z"
  generation: 15
  name: metronome-prod
  namespace: argocd
  resourceVersion: "732501"
  uid: d641a5be-e54b-42de-8577-c65562f9700e
spec:
  destination:
    namespace: metronome-prod
    server: https://kubernetes.default.svc
  project: metronome-prod
  source:
    path: k8s/gitops/overlays/prod
    repoURL: https://github.com/kirbytran12324/autoscaling-final-lab.git
    targetRevision: main
  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true
status:
  controllerNamespace: argocd
  health:
    lastTransitionTime: "2026-09-21T06:48:17Z"
    status: Healthy
  history:
  - deployStartedAt: "2026-09-21T06:48:02Z"
    deployedAt: "2026-09-21T06:48:04Z"
    id: 0
    initiatedBy:
      automated: true
    revision: 17b36b4a79f88fedf781f3de67531bc965c025dc
    source:
      path: k8s/gitops/overlays/prod
      repoURL: https://github.com/kirbytran12324/autoscaling-final-lab.git
      targetRevision: main
  operationState:
    finishedAt: "2026-09-21T06:48:04Z"
    message: successfully synced (all tasks run)
    operation:
      initiatedBy:
        automated: true
      retry:
        limit: 5
      sync:
        prune: true
        revision: 17b36b4a79f88fedf781f3de67531bc965c025dc
        source:
          path: k8s/gitops/overlays/prod
          repoURL: https://github.com/kirbytran12324/autoscaling-final-lab.git
          targetRevision: main
    phase: Succeeded
    startedAt: "2026-09-21T06:48:02Z"
    syncResult:
      resources:
      - group: ""
        hookPhase: Succeeded
        kind: Namespace
        message: namespace/metronome-prod created
        name: metronome-prod
        namespace: metronome-prod
        status: Synced
        syncPhase: Sync
        version: v1
      - group: ""
        hookPhase: Succeeded
        kind: ConfigMap
        message: configmap/metronome-config created
        name: metronome-config
        namespace: metronome-prod
        status: Synced
        syncPhase: Sync
        version: v1
      - group: ""
        hookPhase: Running
        kind: Service
        message: service/metronome-simulator created
        name: metronome-simulator
        namespace: metronome-prod
        status: Synced
        syncPhase: Sync
        version: v1
      - group: apps
        hookPhase: Running
        images:
        - metronome-simulator:phase10
        kind: Deployment
        message: deployment.apps/metronome-simulator created
        name: metronome-simulator
        namespace: metronome-prod
        status: Synced
        syncPhase: Sync
        version: v1
      revision: 17b36b4a79f88fedf781f3de67531bc965c025dc
      source:
        path: k8s/gitops/overlays/prod
        repoURL: https://github.com/kirbytran12324/autoscaling-final-lab.git
        targetRevision: main
  reconciledAt: "2026-09-21T06:53:17Z"
  resourceHealthSource: appTree
  resources:
  - kind: ConfigMap
    name: metronome-config
    namespace: metronome-prod
    status: Synced
    syncWave: -1
    version: v1
  - kind: Namespace
    name: metronome-prod
    status: Synced
    syncWave: -2
    version: v1
  - kind: Service
    name: metronome-simulator
    namespace: metronome-prod
    status: Synced
    version: v1
  - group: apps
    kind: Deployment
    name: metronome-simulator
    namespace: metronome-prod
    status: Synced
    version: v1
  sourceHydrator: {}
  sourceType: Kustomize
  summary: {}
  sync:
    comparedTo:
      destination:
        namespace: metronome-prod
        server: https://kubernetes.default.svc
      source:
        path: k8s/gitops/overlays/prod
        repoURL: https://github.com/kirbytran12324/autoscaling-final-lab.git
        targetRevision: main
    revision: 17b36b4a79f88fedf781f3de67531bc965c025dc
    status: Synced
