apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: autoscaling-lab

resources:
  - ../base
  - horizontal-pod-autoscaler.yaml
  - namespace.yaml
images:
  - name: metronome-simulator
    newTag: phase10
patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: metronome-simulator
    patch: |-
      - op: remove
        path: /spec/replicas