import type {RunDetail} from '../types';
import {ReportSection, Metric} from './shared';

export function RunDetails({run}: {run: RunDetail}) {
  const statistics = run.report.statistics;
  return <ReportSection id="details" title="Run details" subtitle="Canonical configuration, timing, methodology, and reproducibility context.">
    <details className="disclosure"><summary>Configuration and timing</summary><div className="metric-grid detail-metrics">
      <Metric label="Run ID" value={run.runId} /><Metric label="Mode" value={run.mode} /><Metric label="Tournament seed" value={run.tournamentSeed} /><Metric label="Started" value={run.startedAt} /><Metric label="Completed" value={run.completedAt} /><Metric label="Wall-clock span" value={statistics.formatted.wallClock} detail="Includes possible interruption and recovery time" /><Metric label="Rules version" value={run.rulesVersion} /><Metric label="Simulator version" value={run.simulatorVersion} /><Metric label="Simulator image" value={run.simulatorImage} /><Metric label="Runner concurrency" value={run.runnerConcurrency} />
    </div><div className="callout"><strong>Wall-clock interpretation.</strong> The span from <code>startedAt</code> to <code>completedAt</code> may include interruption, diagnosis, and recovery time; it is not active runner execution time.</div></details>
    <details className="disclosure"><summary>Outcome and duration statistics</summary><div className="metric-grid detail-metrics">
      <Metric label="Wins" value={statistics.wins} /><Metric label="Draws" value={statistics.draws} /><Metric label="Turn-cap terminations" value={statistics.turnCaps} /><Metric label="Terminal battle failures" value={statistics.terminalFailures} /><Metric label="Minimum battle duration" value={statistics.formatted.minimum} /><Metric label="Mean battle duration" value={statistics.formatted.mean} /><Metric label="Median battle duration" value={statistics.formatted.median} /><Metric label="p95 battle duration" value={statistics.formatted.p95} /><Metric label="p99 battle duration" value={statistics.formatted.p99} /><Metric label="Maximum battle duration" value={statistics.formatted.maximum} />
    </div></details>
    <details className="disclosure"><summary>Slowest accepted simulations</summary><p>These are individual observations, not a per-Pod performance comparison.</p><div className="table-wrap"><table><thead><tr><th>Match ID</th><th>Participants</th><th>Duration</th><th>Turns</th><th>Reported hostname</th></tr></thead><tbody>{statistics.slowest.map(item => <tr key={item.matchId}><td><code className="truncate" title={item.matchId}>{item.matchId}</code></td><td>{item.pokemon1} vs {item.pokemon2}</td><td>{item.formattedDuration}</td><td>{item.turns}</td><td>{item.servedBy}</td></tr>)}</tbody></table></div></details>
    <details className="disclosure"><summary>Methodology, sources, and limitations</summary><dl><dt>Generated at</dt><dd>{run.report.generatedAt}</dd><dt>Source artifacts</dt><dd>{run.report.sourceFiles.join(', ')}</dd><dt>Authority</dt><dd><code>results.jsonl</code> remains authoritative for accepted simulations; this online view is derived and regenerable.</dd><dt>Tournament scope</dt><dd>This report represents the supplied {run.mode}-mode tournament.</dd><dt>Report behavior</dt><dd>Read-only. The browser requests bounded projections from the explorer API and modifies no tournament artifact.</dd><dt>Ordering</dt><dd>Persisted result ordering may reflect bounded concurrent completion order. Match IDs and accepted-result uniqueness determine authority.</dd><dt>Limitations</dt><dd>Reported hostname and duration values are operational observations, not deterministic replay fields or lifecycle telemetry.</dd></dl></details>
  </ReportSection>;
}
